### ISSUE TITLE
Глянь вк :D

### ISSUE THREAD

**Issue by SantaGitHub** [fewizz/some-cpp-stuff#1]

**Comment by fewizz** [comment]
не могу =P

**Comment by fewizz** [comment]
можешь прямо сюда писать, либо на почту

**Comment by SantaGitHub** [comment]
Можешь передать свою репу Svarka на мой акк?

**Comment by fewizz** [comment]
нет прав? любой может делать с ней что хочет, там ведь даже лицензии нет

**Comment by SantaGitHub** [comment]
народ просто глупый и считает, что если я форкнул - то не я автор ядра ._.

**Comment by SantaGitHub** [comment]
не, если ты не хочешь отдавать репу - то окей

**Comment by fewizz** [comment]
могу в ридми оставить ссыль на репу в гитлабе

**Comment by SantaGitHub** [comment]
хм. окей. Просто думал что просто передашь репу.

**Comment by SantaGitHub** [comment]
@fewizz а мог бы сварку заархиваровать?)
